window.ARIKARA = {
  genres: [
    "Afro Trap",
    "Afro Trap Dembow",
    "Dembow Reggaeton",
    "Flamenco Drill",
    "Flamenco Drill Afrotrap",
    "Flamenco Experimental",
    "Flamenco Hip Hop",
    "Flamenco Reggaeton",
    "Flamenco Trap Soul",
    "Melodic Trap",
    "Rap Flamenco",
    "Reggaeton",
    "Trap",
    "Trap Flamenco"
  ],
  beats: [
    {
      id: "ab-001",
      slug: "costa-del-sol",
      title: "Delaossa Type Beat - \"Costa Del Sol\"",
      bpm: 88,
      key: "F minor",
      genre: "Rap Flamenco",
      tags: ["typebeat", "delaossa", "flamenco", "rap", "instrumental", "beat andaluz"],
      moods: ["cálido", "melódico"],
      cover: "./assets/covers/costa-del-sol.jpg",
      preview: "./assets/audio/costa-del-sol-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "sold",
      createdAt: "2026-02-03"
    },
    {
      id: "ab-002",
      slug: "luna-mora",
      title: "Maka Type Beat - \"Luna Mora\"",
      bpm: 91,
      key: "G minor",
      genre: "Flamenco Reggaeton",
      tags: ["typebeat", "maka", "flamenco", "reggaeton", "instrumental"],
      moods: ["nocturno", "melódico"],
      cover: "./assets/covers/luna-mora.jpg",
      preview: "./assets/audio/luna-mora-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-02-06"
    },
    {
      id: "ab-003",
      slug: "feria-y-oro",
      title: "Dellafuente Type Beat - \"Feria y Oro\"",
      bpm: 73,
      key: "G minor",
      genre: "Flamenco Experimental",
      tags: ["typebeat", "dellafuente", "flamenco", "experimental", "instrumental"],
      moods: ["nostalgico", "etereo"],
      cover: "./assets/covers/feria-y-oro.jpg",
      preview: "./assets/audio/feria-y-oro-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-02-10"
    },
    {
      id: "ab-004",
      slug: "la-calle-mi-casa",
      title: "Central Cee x Morad Type Beat - \"La Calle Mi Casa\"",
      bpm: 72,
      key: "C minor",
      genre: "Flamenco Drill",
      tags: ["typebeat", "central cee", "morad", "flamenco", "drill", "instrumental"],
      moods: ["oscuro", "tenso"],
      cover: "./assets/covers/la-calle-mi-casa.jpg",
      preview: "./assets/audio/la-calle-mi-casa-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-02-11"
    },
    {
      id: "ab-010",
      slug: "la-fe",
      title: "Cano Type Beat – \"La Fe\"",
      bpm: 85,
      key: "A minor",
      genre: "Trap Flamenco",
      tags: ["typebeat", "cano", "trap", "flamenco", "guitarra española", "instrumental"],
      moods: ["sentimental", "tranquilo", "profundo"],
      cover: "./assets/covers/la-fe.jpg",
      preview: "./assets/audio/la-fe-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-011",
      slug: "grilletes",
      title: "JC Reyes Type Beat – \"Grilletes\"",
      bpm: 135,
      key: "E minor",
      genre: "Afro Trap Dembow",
      tags: ["typebeat", "jcreyes", "afrotrap", "dembow", "instrumental", "trap"],
      moods: ["dinámico", "callejero", "contundente"],
      cover: "./assets/covers/grilletes.jpg",
      preview: "./assets/audio/grilletes-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "sold",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-012",
      slug: "crecen",
      title: "Lia Kali Type Beat – \"Crecen\"",
      bpm: 93,
      key: "A minor",
      genre: "Flamenco Trap Soul",
      tags: ["typebeat", "liakali", "flamenco", "trapsoul", "guitarra española", "instrumental"],
      moods: ["emocional", "melódico", "nostálgico"],
      cover: "./assets/covers/crecen.jpg",
      preview: "./assets/audio/crecen-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-013",
      slug: "pechera",
      title: "Bad Bunny Type Beat – \"Pechera\"",
      bpm: 93,
      key: "A minor",
      genre: "Dembow Reggaeton",
      tags: ["typebeat", "badbunny", "reggaeton", "dembow", "latin", "instrumental"],
      moods: ["energético", "club", "pegadizo"],
      cover: "./assets/covers/pechera.jpg",
      preview: "./assets/audio/pechera-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-014",
      slug: "impala",
      title: "Israel B Type Beat – \"Impala\"",
      bpm: 144,
      key: "F minor",
      genre: "Trap",
      tags: ["typebeat", "israelb", "trap", "808", "dark", "instrumental"],
      moods: ["oscuro", "contundente", "americano"],
      cover: "./assets/covers/impala.jpg",
      preview: "./assets/audio/impala-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-015",
      slug: "fatiga",
      title: "Faenna Type Beat – \"Fatiga\"",
      bpm: 90,
      key: "A minor",
      genre: "Rap Flamenco",
      tags: ["typebeat", "faenna", "flamenco", "rap", "hiphop", "instrumental"],
      moods: ["callejero", "emocional", "crudo"],
      cover: "./assets/covers/fatiga.jpg",
      preview: "./assets/audio/fatiga-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-016",
      slug: "pole-position",
      title: "Eladio Carrion Type Beat – \"Pole Position\"",
      bpm: 140,
      key: "E minor",
      genre: "Melodic Trap",
      tags: ["typebeat", "eladiocarrion", "trap", "melodic", "piano", "instrumental"],
      moods: ["emocional", "serio", "melódico"],
      cover: "./assets/covers/pole-position.jpg",
      preview: "./assets/audio/pole-position-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-017",
      slug: "habibi",
      title: "Maka Type Beat – \"Habibi\"",
      bpm: 95,
      key: "A minor",
      genre: "Flamenco Reggaeton",
      tags: ["typebeat", "maka", "reggaeton", "flamenco", "latin", "instrumental"],
      moods: ["pegadizo", "latino", "emocional"],
      cover: "./assets/covers/habibi.jpg",
      preview: "./assets/audio/habibi-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-018",
      slug: "jungla-de-plata",
      title: "Dellafuente x Rels B Type Beat – \"Jungla de Plata\"",
      bpm: 90,
      key: "B minor",
      genre: "Flamenco Hip Hop",
      tags: ["typebeat", "dellafuente", "relsb", "flamenco", "hiphop", "instrumental"],
      moods: ["emocional", "melódico", "orgánico"],
      cover: "./assets/covers/jungla-de-plata.jpg",
      preview: "./assets/audio/jungla-de-plata-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-03"
    },
    {
      id: "ab-019",
      slug: "el-bloque",
      title: "RVFV Type Beat – \"El Bloque\"",
      bpm: 107,
      key: "D minor",
      genre: "Afro Trap",
      tags: ["typebeat", "rvfv", "afrotrap", "trap", "instrumental"],
      moods: ["callejero", "enérgico", "melódico"],
      cover: "./assets/covers/el-bloque.jpg",
      preview: "./assets/audio/el-bloque-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-22"
    },
    {
      id: "ab-020",
      slug: "sin-matricula",
      title: "Morad Type Beat – \"Sin Matrícula\"",
      bpm: 140,
      key: "C minor",
      genre: "Flamenco Drill",
      tags: ["typebeat", "morad", "flamenco", "drill", "trap", "instrumental"],
      moods: ["callejero", "oscuro", "contundente"],
      cover: "./assets/covers/sin-matricula.jpg",
      preview: "./assets/audio/sin-matricula-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-22"
    },
    {
      id: "ab-021",
      slug: "digital-drama",
      title: "Saiko Type Beat – \"Digital Drama\"",
      bpm: 100,
      key: "A minor",
      genre: "Reggaeton",
      tags: ["typebeat", "saiko", "reggaeton", "melodic", "instrumental"],
      moods: ["melódico", "atmosférico", "sentimental"],
      cover: "./assets/covers/digital-drama.jpg",
      preview: "./assets/audio/digital-drama-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-22"
    },
    {
      id: "ab-022",
      slug: "sauvignon",
      title: "Jul Type Beat – \"Sauvignon\"",
      bpm: 97,
      key: "C minor",
      genre: "Afro Trap",
      tags: ["typebeat", "jul", "afrotrap", "trap", "instrumental"],
      moods: ["nocturno", "melódico", "contundente"],
      cover: "./assets/covers/sauvignon.jpg",
      preview: "./assets/audio/sauvignon-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-22"
    },
    {
      id: "ab-023",
      slug: "vandalia-drive",
      title: "JC Reyes Type Beat – \"Vandalia Drive\"",
      bpm: 138,
      key: "D minor",
      genre: "Flamenco Drill Afrotrap",
      tags: ["typebeat", "jcreyes", "flamenco", "drill", "afrotrap", "instrumental"],
      moods: ["callejero", "contundente", "oscuro"],
      cover: "./assets/covers/vandalia-drive.jpg",
      preview: "./assets/audio/vandalia-drive-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-22"
    },
    {
      id: "ab-024",
      slug: "azahar",
      title: "Maka Type Beat – \"Azahar\"",
      bpm: 103,
      key: "C minor",
      genre: "Flamenco Reggaeton",
      tags: ["typebeat", "maka", "flamenco", "reggaeton", "instrumental"],
      moods: ["melódico", "latino", "sentimental"],
      cover: "./assets/covers/azahar.jpg",
      preview: "./assets/audio/azahar-preview.mp3",
      prices: { basic: 29.99, premium: 79.99, exclusive: 299.99 },
      status: "available",
      createdAt: "2026-04-22"
    }
  ],
  licenses: [
    {
      id: "basic",
      name: "Basic",
      price: 29.99,
      priceLabel: "29,99 EUR",
      includes: ["MP3", "WAV", "Uso comercial", "Hasta 100K streams"],
      highlight: false
    },
    {
      id: "premium",
      name: "Premium",
      price: 79.99,
      priceLabel: "79,99 EUR",
      includes: ["MP3", "WAV", "STEMS", "Uso comercial", "Hasta 500K streams"],
      highlight: true
    },
    {
      id: "exclusive",
      name: "Exclusive",
      price: 299.99,
      priceLabel: "Desde 299,99 EUR",
      includes: ["MP3", "WAV", "STEMS", "Uso comercial", "Streams ilimitados", "Full rights"],
      highlight: false,
      disabled: true
    }
  ],
  services: [
    {
      id: "basic",
      name: "Basic",
      priceLabel: "79,99 EUR / canción",
      includes: ["Mixing", "Mastering", "Por stems/pistas"],
      highlight: false
    },
    {
      id: "premium",
      name: "Premium",
      priceLabel: "129,99 EUR / canción",
      includes: ["Mixing", "Mastering", "Por stems/pistas", "Arreglos", "Producción"],
      highlight: false
    },
    {
      id: "pro",
      name: "Pro",
      priceLabel: "199,99 EUR / canción",
      includes: ["Mixing", "Mastering", "Por stems/pistas", "Arreglos", "Producción", "Tratamiento vocal"],
      highlight: true
    }
  ]
};
